services:
  db:
    container_name: mysql
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_DATABASE: api
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
 
  api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - PROFILE=dev
      - DATABASE_URL=jdbc:mysql://db:3306/api?createDatabaseIfNotExist=true
      - DATABASE_USER=root
      - DATABASE_PWD=root_pass
 
volumes:
  db_data:
